# Generated by Django 4.1.3 on 2022-12-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publicated',
            field=models.BooleanField(default=False),
        ),
    ]
